apiVersion: v1
kind: PersistentVolume
metadata:
  name: mautic-config-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mautic/config"
