apiVersion: v1
kind: Pod
metadata:
  name: mautic-server
  labels:
    app: mautic-server
spec:
  containers:
  - name: mautic-server
    image: mautic/mautic:v4
    env:
    - name: MAUTIC_DB_HOST
      value: mysql.default.svc.cluster.local
    - name: mautic
      value: mautic
    - name: MAUTIC_DB_USER
      value: root
    - name: MAUTIC_DB_PASSWORD
      value: password
    

