apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye-pipeline
spec:
  params:
  - name: username
    type: string
    default: teste-pipeline
  tasks:
    - name: hello
      taskRef:
        name: hello-task
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbye-task
      params:
      - name: username
        value: $(params.username)