apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-goodbye-pipelinerun
spec:
  pipelineRef:
    name: hello-goodbye-pipeline
  params:
  - name: username
    value: "Tekton testing pipelinerun"