apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-goodbye-eventlistener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: hello-goodbye-trigger 
      bindings:
      - ref: hello-goodbye-triggerbinding
      template:
        ref: hello-goodbye-triggertemplate