apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  labels:
    app: n8n
    component: configmap
data:
  NODE_ENV: "production"
  N8N_PORT: "5678"
  N8N_HOST: "n8n.local.gd"
  N8N_EDITOR_BASE_URL: "http://n8n.local.gd/"
  GENERIC_TIMEZONE: "America/Sao_Paulo"
  DB_TYPE: "mysqldb"
  DB_MYSQLDB_HOST: "mysql.default.svc.cluster.local"
  DB_MYSQLDB_PORT: "3306"
  DB_MYSQLDB_DATABASE: "n8n"
  DB_MYSQLDB_USER: "root"
